FROM golang:alpine AS build

RUN apk add git

RUN mkdir /src
ADD . /src
WORKDIR /src

RUN go build -o /tmp/server ./cmd/grpc/main.go

FROM alpine:edge

COPY --from=build /tmp/server /sbin/server

CMD /sbin/server
